### PR TITLE
Add code coverage.

### PR DESCRIPTION
**Pull request by marcofavorito**
This PR improves CI and development scripts by adding code coverage to the development build.

You can try it locally with `scripts/build-dev.sh`

### CODE REVIEW

**Comment by marcofavorito** [comment]
image

**Comment by francescofuggitti** [comment]
I tried changes locally, but got some errors.

System:
- macOS Catalina 10.15.3

**Comment by marcofavorito** [comment]
Fixes #11

**Comment by francescofuggitti** [comment]
Great work! However, _ci-configure.sh and build-dev.sh still don't work on macOS since readlink's option `-e`  is not supported by the system.

Let's continue with these scripts and use Linux as main platform. Others will use Docker..

**Comment by marcofavorito** [comment]
> Great work! However, _ci-configure.sh and build-dev.sh still don't work on macOS since readlink's option `-e` is not supported by the system.
> 
> Let's continue with these scripts and use Linux as main platform. Others will use Docker..

Hi @francescofuggitti, I removed `readlink` usage from the scripts.

**Pull request merged**
